function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Auto-generated by MATLAB, 26-Feb-2026 00:30:46.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx3 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx1 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [0;0;0.15];
x1_step1.gain = [2;2;2.35294117647059];
x1_step1.ymin = -1;

% Layer 1
b1 = [0.075616540818988497996;-14.060508448670631765;-11.167841214716098364;-4.1523033410565162171;-13.416148214560829288;-14.765755198815982752;-0.022821925954153277072;-18.611506752806764808;0.28285132465551277026;-0.79101598981224430229];
IW1_1 = [3.3982785104867074821 -0.015492257331374565538 -1.4625545297992874616;3.7993804187560473729 -12.635382783260157069 5.3672953094386519624;35.172764827418824041 -0.0022829161706743161114 2.982595207058098552;3.3661316452727239046 -0.46310948094771386963 9.9945703466766673273;3.5801037308562784212 -11.973228212263871129 5.1330086176353155736;-4.0703388770955282183 -5.6523422787802832801 10.87805507225094459;-3.2876041916296343537 -0.030932340886855730355 0.98217989980070807832;-32.922819976160646149 0.16031463825139519175 -0.10269696406472032801;3.3988592198813161183 0.065309288357260825153 -0.76620758956763890257;-3.9360227967693210971 -0.072112688770173641317 0.90663807784275018964];

% Layer 2
b2 = -0.38962775218667128341;
LW2_1 = [-2.2099444290727698892 5.9274278879262594089 0.34048600292571634673 -0.56856664646831400756 -6.5733161338548828923 0.58063489213980723491 -6.1802533262518810631 -0.46001321307565584684 -5.931158031101543493 -2.3939801290284616897];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 0.37371688968579;
y1_step1.xoffset = 0.366666666666667;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS

    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);

    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);

    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;

    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
